### ISSUE TITLE
plugin fails with modification check - MMM not understood by the plugin. 

### ISSUE THREAD

**Issue by nzCharlie** [ashwanthkumar/gocd-build-github-pull-requests#123] opened 2018-07-30 23:28 UTC
The stash.pr plugin fails with modification check. 

Modification check failed for material: [url=ssh://git@bitbucket.xxxxx.co.nz:1234/xx/xxxx-xxxx.git]31 Jul, 2018 at 11:23:12 Local Time

Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'latest-revisions-since'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '"Unable to parse git-diff-tree output line: MMM\tapp/xxx/src/main/webapp/xxxx/xxx.jsp\nFrom output:\n a8fec4675bfdf4770aceafa6015abf475d3e6608\nMMM\tapp/xxx/src/main/webapp/xxxx/xxx.jsp"']

Looking into the code, it seems like **MMM** returned by git command is not understood by the plugin.

**Comment by williamsbdev** [comment] 2018-09-04 16:45
@nzCharlie and @ashwanthkumar - I'm also experiencing this. Took me a while to dig into what the root cause of the error was (was simply getting an NPE in the go-server.log that distracted me for a while). I believe the fix is here:

https://github.com/ashwanthkumar/git-cmd/blob/master/src/com/tw/go/plugin/git/GitCmdHelper.java#L24

changing it from:

`private static final Pattern GIT_DIFF_TREE_PATTERN = Pattern.compile("^(.{1,2})\\s+(.+)$");`

to:

`private static final Pattern GIT_DIFF_TREE_PATTERN = Pattern.compile("^(.{1,3})\\s+(.+)$");`

@ashwanthkumar thoughts?

**Comment by williamsbdev** [comment] 2018-10-10 19:27
@ashwanthkumar - Now that https://github.com/ashwanthkumar/git-cmd/pull/3 has been merged, what is the process to get this plugin updated with that new jar and published?

**Comment by ashwanthkumar** [comment] 2018-10-12 00:59
@williamsbdev I would need to publish a new version of `git-cmd` and use that version in here. Please give me a few days, I'll sort them out and share an update in here once a new release is available.

**Comment by williamsbdev** [comment] 2018-11-04 19:54
@ashwanthkumar - Is there anything I can do to help get this published?

**Comment by ashwanthkumar** [comment] 2018-11-05 04:55
@williamsbdev I've made a new release with the changes in [here](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/tag/v1.4.0-RC2). Please do test it out and let me know if it works as expected. Once you confirm, I'll cut a full 1.4.0 release out of this RC.

**Closed by ashwanthkumar** 2018-11-05 04:55 UTC

**Comment by williamsbdev** [comment] 2018-11-05 12:17
@ashwanthkumar - This has resolved our issues. Thanks for getting this published!

From my testing, this is ready for a release but please do any other testing that may be needed.

@nzCharlie - This RC fixed the issue you and I had.
