### ISSUE TITLE
Build devel branch instead of master for baseline for pull requests

### ISSUE THREAD

**Issue by jefftrimm** [ashwanthkumar/gocd-build-github-pull-requests#77] opened 2016-10-12 20:45 UTC
In gitflow, pull requests are to merge to devel branch instead of master branch.  In this case, we want the plugin to specify a branch other than master to use as a baseline initially build devel branch instead of master.

**Comment by ashwanthkumar** [comment] 2016-10-14 17:02
Duplicate of #66. Closing this and tracking it as part of that.

**Closed by ashwanthkumar** 2016-10-14 17:02 UTC
