### ISSUE TITLE
GoCD job will fails when there have no pull request in github

### ISSUE THREAD

**Issue by yunlzheng** [ashwanthkumar/gocd-build-github-pull-requests#59] opened 2015-12-04 13:56 UTC
The Go-Agent log as follow:

```
2015-12-04 21:19:08,527 [loopThread] ERROR thoughtworks.go.work.DefaultGoPublisher:137 - Interaction with plugin with id 'github.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, xxxx.git, /var/lib/go-agent/pipelines/x] - null"']xxx
java.lang.RuntimeException: Interaction with plugin with id 'github.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, xxxx.git, /var/lib/go-agent/pipelines/xxxx] - null"']
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:38)
        at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:175)
        at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
        at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
        at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
        at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
        at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
        at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
        at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, xxxx.git, /var/lib/go-agent/pipelines/xxxx] - null"'
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:36)
        ... 16 more
```

**Comment by ashwanthkumar** [comment] 2015-12-13 04:42
By default the plugin will build against the `master` branch. From the logs looks like the checkout from master is failing. Any idea why? Does your repo not have a master branch?

**Comment by ashwanthkumar** [comment] 2015-12-13 04:43
It would be nice if you can share the plugin logs as well. They're generally named with `plugin` prefix under the same location where the Go logs are present.

**Comment by ccampanale** [comment] 2016-01-26 17:43
I'm having a similar issue here and I can answer the question you asked for my environment. No, the repo in our case does not have a master branch but another branch named `production` which is set to the default. Is there any way to specific the branch name you are monitoring or have the plugin get the default branch name and used that instead of master?

**Comment by srinivasupadhya** [comment] 2016-01-27 02:19
there is no way way to do that currently. @ashwanthkumar need to check if there is a way to checkout to default branch instead of we checking out "master"

**Comment by ccampanale** [comment] 2016-01-27 20:26
Just to follow-up here, the default branch idea is pretty much the safest bet here overall (at least to avoid these errors which in our case resulted in an inordinate about of flywheel directories being created which actually filled up the drive on our test GoCD server, lol). That being said, in my opinion, an option when configuring the github pipeline material to specify the branch to be monitored would be very nice. 

**Bit of Background**
In my particular case I have an application residing in a Github repo with two protected branches: qa and production. I want to setup my pipelines such that some things are done (build, unit testing, etc) when a PR to the QA branch is submitted. Once the commits have successful status checks and the code is merged (pipeline success and git materials in another pipeline) then the workflow continues with deploys to the QA environment, some UAT, etc.. Then further work is done to merge this code into production but I don't necessarily need the very first pipeline being kicked off with every PR. 

I hope that makes sense. I'm also new to GoCD and still learning the ins and outs.

**Comment by arvindsv** [comment] 2016-05-16 21:42
I think this is related to #66.

**Closed** 2017-02-25 08:53 UTC

**Comment by dokaspar** [comment] 2018-03-16 14:01
Just curious... is it supposed to be `--branch\u003dmaster` in the log file? Isn't that an encoding problem? I cannot execute `git clone --branch\u003dmaster <url>`, it only works properly with `--branch=master`.

**Comment by takeda** [comment] 2018-05-08 22:57
@dokaspar probably this is just encoding \u003d translates to = sign.

BTW: I don't think this issue was resolved or at least I'm getting a similar one:

```
2018-05-08 22:49:50,287 WARN  [95@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:112 - [Material Update] Modification check failed for material: [url=git@xxx.git]
java.lang.RuntimeException: Interaction with plugin with id 'github.pr' implementing 'scm' extension failed while requesting for 'latest-revision'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, git@xxx.git, /var/lib/go-server/pipelines/flyweight/xxx] - null"']
  at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:42)
  at com.thoughtworks.go.plugin.access.scm.SCMExtension.getLatestRevision(SCMExtension.java:109)
  at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.latestModification(PluggableSCMMaterialPoller.java:62)
  at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.latestModification(PluggableSCMMaterialPoller.java:47)
  at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:105)
  at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
  at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:55)
  at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:69)
  at com.thoughtworks.go.server.materials.PluggableSCMMaterialUpdater.addNewMaterialWithModifications(PluggableSCMMaterialUpdater.java:66)
  at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:163)
  at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:121)
  at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater.java:47)
  at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:88)
  at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
  at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
  at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
  at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:85)
  at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:50)
  at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:30)
  at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
  at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, git@xxx.git, /var/lib/go-server/pipelines/flyweight/xxx] - null"'
  at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:40)
  ... 22 common frames omitted
```

In my case there is a master branch for that repo, but the default one is set to develop. Although perhaps this is not the cause because the plugin seems to work with other repos which are similarly set up.

The version used is 1.3.3 which according to release log includes above fix.

**Comment by takeda** [comment] 2018-05-08 22:59
This issue was discovered after a while when flywheel directory got 32 thousand entries (apparently the maximum number of files/directories in ext3 file system.

**Comment by ashwanthkumar** [comment] 2018-05-16 04:52
@arvindsv I guess the root cause is at https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/122. 

I have not been able to reproduce this from my side actually.
