### ISSUE TITLE
Unable to configure for private repository

### ISSUE THREAD

**Issue by jeisen** [ashwanthkumar/gocd-build-github-pull-requests#49] opened 2015-08-26 21:52 UTC
I'm attempting to create PR pipelines for private GitHub repositories. I already have them all set up using the standard Git material configuration, using the SSH endpoints and with the private key stored in ~/.ssh.

I've set up a pipeline using the PR plugin, and have tried using both the http and ssh endpoints, and using a ~/.github with both standard user/password auth and OAuth. All combinations give the same error from the server:

```
Modification check failed for material: [url=git@github:<my_repo>.git] [Aug-24 19:15:06]
Interaction with plugin with id 'github.pr' implementing 'scm' extension failed while requesting for 'latest-revision'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"clone failed"']
```

The stacktrace shows this:

```
2015-08-24 19:10:36,910  INFO [84@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - Flyweight: /var/lib/go-server/pipelines/flyweight/6e32a058-b36b-4344-969a-ca90b204caa2
2015-08-24 19:10:36,959  WARN [84@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:67 - get latest revision: 
java.lang.RuntimeException: clone failed
at com.tw.go.plugin.jgit.JGitHelper.cloneRepository(JGitHelper.java:67)
at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:38)
at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleGetLatestRevision(GitHubPRBuildPlugin.java:161)
at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:86)
at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
at com.thoughtworks.go.plugin.access.scm.SCMExtension.getLatestRevision(SCMExtension.java:137)
at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.latestModification(PluggableSCMMaterialPoller.java:61)
at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.latestModification(PluggableSCMMaterialPoller.java:46)
at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:106)
at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:72)
at com.thoughtworks.go.server.materials.PluggableSCMMaterialUpdater.addNewMaterialWithModifications(PluggableSCMMaterialUpdater.java:66)
at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:178)
at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:134)
at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater. java:47)
at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:95)
at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:92)
at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:48)
at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:29)
at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.<my_repo>.git: Auth fail
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
at com.tw.go.plugin.jgit.JGitHelper.cloneRepository(JGitHelper.java:65)
... 31 more
Caused by: org.eclipse.jgit.errors.TransportException: g...@github.com:<my_repo>.git: Auth fail
at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
... 34 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
at com.jcraft.jsch.Session.connect(Session.java:512)
at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
... 41 more
```

This only seems to be happening with private repositories. If I try a public one, it moves forward properly. I've verified that the login credentials are correct and have access to the repos.

**Comment by ashwanthkumar** [comment] 2015-08-28 14:08
@jeisen Can you please let me know the Go CD version and plugin version you're using?

**Comment by jeisen** [comment] 2015-08-28 14:12
GoCD: 15.2.0(2248-c1f90a6aa3192a)
Plugin: 1.2

**Comment by ashwanthkumar** [comment] 2015-08-28 14:17
We're still on GoCD 15.1 version and it is working fine on our setup. Will check out over the weekend and keep you posted.

**Comment by albertpastrana** [comment] 2015-09-03 11:27
@ashwanthkumar did you have a chance to take a look at that? We are facing the same problem and downgrading to 15.2 would be painful as we want to use the github auth plugin as well (which requires GoCD >= 15.2)

**Comment by albertpastrana** [comment] 2015-09-03 14:24
Btw, after some (too much) struggling we've seen the problem was ours as we had a problem with the repo url and the token.
It's working now with 15.2 without problems.

**Comment by jeisen** [comment] 2015-09-03 16:25
@albertpastrana Can you share exactly what it was that was the problem, or how you found it? We're still facing this issue and has become a blocker large enough to abandon GoCD for the moment.

**Comment by ashwanthkumar** [comment] 2015-09-03 18:29
@jeisen Sorry for the delay in response. I just upgraded our internal setup to GoCD 15.2.0(2248-c1f90a6aa3192a) and 1.2 version of the plugin and it works fine for our private repos on Github. Actually the plugin wouldn't use jGit if it can find `git` in PATH. [This](https://github.com/srinivasupadhya/git-cmd/blob/master/src/com/tw/go/plugin/HelperFactory.java#L13) code path ensures that. 
Can you tell me what does "Check Connection" button the Material popup say? That validates ~/.github and Github url connectivity.

**Comment by ashwanthkumar** [comment] 2015-09-03 18:30
Also from the logs I see `git@github:<my_repo>.git`, are you using just `github` with special PEM file configured on `~/.ssh/config` or was it just a typo?

**Comment by ashwanthkumar** [comment] 2015-09-03 18:31
@albertpastrana Even I'm curious to know what the problem was, may be something I can add to README as FAQs.

**Comment by jeisen** [comment] 2015-09-03 22:14
@ashwanthkumar Yes, sorry, that was me deleting too much in obfuscating the real repo name.

 org.eclipse.jgit.errors.TransportException: git@github.com:<myrepo>.git: Auth fail

**Comment by jeisen** [comment] 2015-09-03 22:19
Check Connection gives "Could connect to URL successfully"

We do have git in the global path. I have go-server running inside a Docker container that runs '/usr/share/go-server/server.sh' in a shell, which should not have any issue seeing git in the path.

**Comment by ashwanthkumar** [comment] 2015-09-04 05:47
@jeisen We just released `v1.2.1`. In this we've moved away from jGit completely. Please do try that and let me know if that helps. 

Meanwhile, if you could share some details on docker-GoCD integration, I could try replicating the issue locally.

**Comment by ashwanthkumar** [comment] 2015-09-04 05:53
@jeisen I just stumbled upon this issue today on a different context. The private key has been [added to ssh-agent](https://help.github.com/articles/generating-ssh-keys/#step-3-add-your-key-to-the-ssh-agent) right?

**Comment by albertpastrana** [comment] 2015-09-04 07:34
@jeisen @ashwanthkumar it was actually a silly mistake but somehow we had some problems troubleshooting it.

We were connecting to a github private repo. When we did setup the material we entered the url as `https` instead of `git` and performed the validation of the connection. It was successful.

Later, when running the pipeline, we were seeing an error staying that it was unable to clone. It was weird as the "check connection" did work.  We also tested the clone of the repo in the agent command line using the https url and the same credentials and it did work.

Finally, we changed the url in the material to git instead of https and it everything worked.

**Comment by prisamuel** [comment] 2015-09-16 08:28
I see the same issue pulling from a private repository with the latest (v.1.2.1 git-pull-request-builder) and the GoCD version 15.2.0.

I've set up the file ~/.github with my oauth token. I'm able to build PR's from public repositories but not from private github repositories. 

Here's the error message from GoCD's console:
Modification check failed for material: [url=https://github.com/private-repo/blah.git] [Sep-16 08:27:00]
Interaction with plugin with id 'github.pr' implementing 'scm' extension failed while requesting for 'latest-revision'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, https://github.com/private-repo/blalh.git, /var/lib/go-server/pipelines/flyweight/c089bd48-6dd8-4923-994d-680ef215c72f] - null"']

**Comment by ashwanthkumar** [comment] 2015-09-16 11:56
@prisamuel Looks like you're using HTTPS based url. Can you try using the SSH url for the repo?

**Comment by ashwanthkumar** [comment] 2015-09-16 12:00
We don't have support for doing HTTPs urls now that we're using only Git command line tool.

**Comment by prisamuel** [comment] 2015-09-16 12:29
The first try was with the git ssh url. I get very similar errors. 

Modification check failed for material: [url=git@github.com:private-repo/blah.git] [Sep-16 12:27:00]
Interaction with plugin with id 'github.pr' implementing 'scm' extension failed while requesting for 'latest-revision'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, git@github.com:private-repo/blah.git, /var/lib/go-server/pipelines/flyweight/92b79fc8-fbb3-4561-882b-ce08a7dc5b02] - null"']

**Comment by ashwanthkumar** [comment] 2015-09-16 12:32
@prisamuel Can you check the plugin.github.pr.log? Also, does the command work normally when executed via Shell?

**Comment by prisamuel** [comment] 2015-09-16 13:05
I checked the command line git clone with the https url using the oauth token and it works. With the ssh url, the git clone shell command doesn't  take the token.

Here's the log from plugin.github.pr.log : 
`
2015-09-16 13:04:00,381  INFO [91@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - Flyweight: /var/lib/go-server/pipelines/flyweight/27ef9622-228d-4e1a-9db1-1e80c0d05a8e
2015-09-16 13:04:00,415  WARN [91@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:67 - get latest revision: 
java.lang.RuntimeException: Exception Occurred: [git, clone, --branch=master, git@github.com:private-repo/blah.git, /var/lib/go-server/pipelines/flyweight/27ef9622-228d-4e1a-9db1-1e80c0d05a8e] - null
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
	at com.tw.go.plugin.git.GitCmdHelper.runAndGetOutput(GitCmdHelper.java:397)
	at com.tw.go.plugin.git.GitCmdHelper.cloneRepository(GitCmdHelper.java:55)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:38)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleGetLatestRevision(GitHubPRBuildPlugin.java:161)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:86)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.getLatestRevision(SCMExtension.java:137)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.latestModification(PluggableSCMMaterialPoller.java:61)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.latestModification(PluggableSCMMaterialPoller.java:46)
	at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:106)
	at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:72)
	at com.thoughtworks.go.server.materials.PluggableSCMMaterialUpdater.addNewMaterialWithModifications(PluggableSCMMaterialUpdater.java:66)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:178)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:134)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater.java:47)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:95)
	at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
	at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:92)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:48)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:29)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 128 (Exit value: 128)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
	... 33 more
`

**Comment by ashwanthkumar** [comment] 2015-09-16 13:47
Actually OAuth is used only for making github api calls. Not for repo cloning in https urls. I guess that's a bug on our end. I'll fix that. 

For ssh urls the server's .ssh/id_rsa or id_dsa key must be added on github against an account. This is very similar to default Git material with ssh urls. 

Sent from mobile, excuse any typos

-----Original Message-----

**Comment by ashwanthkumar** [comment] 2015-09-16 13:50
Actually I meant the public key not the private key. Sorry. 

.ssh/id_rsa.pub 

Sent from mobile, excuse any typos

-----Original Message-----

**Comment by ashwanthkumar** [comment] 2015-09-18 10:41
@prisamuel and @jeisen is the new version working for you guys after the changes to use SSH urls? In which case can I close the issue?

**Comment by prisamuel** [comment] 2015-09-21 08:29
Thanks. This is no longer an issue for me. https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/54 would solve the core issue I mentioned earlier.

**Closed** 2015-09-21 08:41 UTC
